export { default as page } from './page'
export { default as category } from './category'
export { default as packages } from './packages'
export { default as title } from './title'
export { default as starWars } from './starWars'
export { default as starWarsPage } from './starWarsPage'
export { default as starWarsSearch } from './starWarsSearch'